
package com.bac.cxf.client.generated_code;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderProcess", targetNamespace = "http://service.cxf.config.bac.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcess {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://service.cxf.config.bac.com/", className = "com.bac.cxf.client.generated_code.ProcessOrder")
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://service.cxf.config.bac.com/", className = "com.bac.cxf.client.generated_code.ProcessOrderResponse")
    public String processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
