
package com.bac.cxf.client.generated_code;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderProcessImplService", targetNamespace = "http://service.cxf.config.bac.com/", wsdlLocation = "http://localhost:8282/services/OrderProcess?wsdl")
public class OrderProcessImplService
    extends Service
{

    private final static URL ORDERPROCESSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bac.cxf.client.generated_code.OrderProcessImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bac.cxf.client.generated_code.OrderProcessImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8282/services/OrderProcess?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8282/services/OrderProcess?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERPROCESSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public OrderProcessImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcessImplService() {
        super(ORDERPROCESSIMPLSERVICE_WSDL_LOCATION, new QName("http://service.cxf.config.bac.com/", "OrderProcessImplService"));
    }

    /**
     * 
     * @return
     *     returns OrderProcess
     */
    @WebEndpoint(name = "OrderProcessImplPort")
    public OrderProcess getOrderProcessImplPort() {
        return super.getPort(new QName("http://service.cxf.config.bac.com/", "OrderProcessImplPort"), OrderProcess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcess
     */
    @WebEndpoint(name = "OrderProcessImplPort")
    public OrderProcess getOrderProcessImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cxf.config.bac.com/", "OrderProcessImplPort"), OrderProcess.class, features);
    }

}
